// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKT_wUm-XkPxQKPAZMMqwUkWxoScAZaa0',
    appId: '1:453164778220:web:ffa6101f54ee69f2b2dbc9',
    messagingSenderId: '453164778220',
    projectId: 'bustrack-d6932',
    authDomain: 'bustrack-d6932.firebaseapp.com',
    storageBucket: 'bustrack-d6932.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0HQdKvM_kLuTTJA833smXLPi6pH7HFns',
    appId: '1:453164778220:android:2805a32237a539bab2dbc9',
    messagingSenderId: '453164778220',
    projectId: 'bustrack-d6932',
    storageBucket: 'bustrack-d6932.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2u1hAh-FwG4VUaQw2R87QAE_VdN-lHa8',
    appId: '1:453164778220:ios:3aeff1dbca6bd9dab2dbc9',
    messagingSenderId: '453164778220',
    projectId: 'bustrack-d6932',
    storageBucket: 'bustrack-d6932.appspot.com',
    iosBundleId: 'com.example.bustrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2u1hAh-FwG4VUaQw2R87QAE_VdN-lHa8',
    appId: '1:453164778220:ios:3aeff1dbca6bd9dab2dbc9',
    messagingSenderId: '453164778220',
    projectId: 'bustrack-d6932',
    storageBucket: 'bustrack-d6932.appspot.com',
    iosBundleId: 'com.example.bustrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKT_wUm-XkPxQKPAZMMqwUkWxoScAZaa0',
    appId: '1:453164778220:web:c0e5189bcfe20c83b2dbc9',
    messagingSenderId: '453164778220',
    projectId: 'bustrack-d6932',
    authDomain: 'bustrack-d6932.firebaseapp.com',
    storageBucket: 'bustrack-d6932.appspot.com',
  );

}